### ISSUE TITLE
Alpha release tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#259]
- [ ] Multi-tabs (PR #234)
  - [x] Fix broken growler alerts (PR #234)
  - [x] Merge conflicts (PR #234)
  - [x] Run reg tests
  - [ ] Update site alerts to use new summary endpoint
- [x] Create new summary endpoint (PR #264)
- [x] HUD errors in dev mode only (PR #265)
- [x] DEBUG in dev mode only (PR #265)
- [x] Remove example options (PR #279)
- [x] Top level README (PR #261)
- [ ] Clean wiki - hide out of date stuff
- [x] Make repo public to zaproxy
  - [x] Trim repo #212
  - [x] Create branches per #246
  - [x] Update links to point to `zaproxy/zap-hud` (e.g. in `README`, `CHANGELOG`).
- [x] Put HUD on Marketplace (dev)

**Comment by dscrobonia** [comment]
lets close this out. I'll reopen a pr with some of the notes form the previous pr message. Thanks!

**Comment by thc202** [comment]
Closing, thank you.
